[package]
name = "codec"
version = "0.1.0"
edition = "2021"

[features]
default = []
binary = ["bincode"]
json = ["serde_json"]

[dependencies]
serde = "1.0.137"
bincode = { version = "1.3.3", optional = true }
serde_json = { version = "1.0.81", optional = true }
